# Miscelaneous
favicon: /favicon.ico

# fancybox gallery
fancybox: true

# main menu navigation
# ====================================
menu:
  home: /
  archive: /archives
  #category: /categories
  #tags: /tags
  about: /about

# site logo introduce and footer quote
# ====================================
logo: Danlili
introduce: "Just Do It"
quote: "停止奋斗， 生命也就停止了。"

# social club
# ====================================
social:
  ##zhihu: https://www.zhihu.com/
  weibo: https://weibo.com/6377106586/profile?rightmod=1&wvr=6&mod=personinfo
  github: https://github.com/jialiiu
  steam:
  linkedin:
  facebook:
  twitter: https://twitter.com/home?lang=zh-cn
  douban:
  tumblr:
  instagram: https://www.instagram.com/ljldaniel_k_ori/?hl=zh-cn 
  stackoverflow:
  rss:

# third party services settings
# ===================================

#leanCloud
leancloud:
  app_id:
  app_key:

# comments
# Valine comment system. https://valine.js.org
valine:
  comment_name: 留言板 #your comment area title
  enable: true # if you want use valine, please set this value to true
  app_id:  # your leancloud appId
  app_key:  # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: retro # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 欢迎留言~ O(∩_∩)O # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

#disqus
disqus_shortname:





# ==================================
version: 1.0
# ==================================
